blueprint:
  name: Window open, climate off after a defined time
  description: An automation that turns off a running your climate device for exmple a heater
    or an air conditioning if a window sensor is open for a specific time. It waits
    until the window is closed again in order to turn the climate entity on again.
  domain: automation
  input:
    window_entity:
      name: Window Sensor
      description: The window sensor that controls the climate entity.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
    minimum_open_time:
      name: Miniumum time the window is open
      description: Time in seconds to wait until the automation is triggered
      default: 12
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
    climate_target:
      name: Climate Device
      description: The climate entity that is controlled by the window sensor.
      selector:
        entity:
          domain: climate
    climate_temperature:
      name: Climate Temperature
      description: The temperature the climate entity is set to.
      selector:
        number:
          min: 4.0
          max: 30.0
          unit_of_measurement: °C
          mode: slider
          step: 1.0
    to_window_state:
      name: To window state
      description: The state the window sensor should be in to trigger the automation.
      default: closed
      selector:
        options:
          - off
          - on
    from_window_state:
      name: From window state
      description: The state the window sensor should comes from
      default: closed
      selector:
        options:
          - off
          - on
trigger:
- platform: state
  entity_id: !input 'window_entity'
  to: !input 'to_window_state'
  for: !input 'minimum_open_time'
condition:
- condition: not
  conditions:
    - condition: state
      entity_id: !input 'climate_target'
      state: !input 'from_window_state'
action:
- service: climate.set_temperature
    data:
      entity_id: !input 'climate_target'
      temperature: !input 'climate_temperature'
- wait_for_trigger:
  - platform: state
    entity_id: !input 'window_entity'
    to: !input 'to_window_state'
  continue_on_timeout: false
- service: climate.turn_on
  entity_id: !input 'climate_target'